apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: debugger-cluster
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["nodes"]
  verbs: ["*"]