kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: debugger-role-rolebinding
  namespace: debugger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: debugger-role
subjects:
- kind: Group
  namespace: debugger
  #name: groupObjectId
  name: "a105d0ea-d120-4b98-9c3a-75a231ed1483"  