apiVersion: v1
kind: Pod
metadata:
  labels:
    env: dev
  name: nginx
  namespace: default
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      limits:
        memory: "300Mi"
        cpu: "125m"
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20
  dnsPolicy: ClusterFirst
  restartPolicy: Always
